#!/bin/bash

case "${1}" in
    "status"|"login"|"lock"|"logout"|"--help"|"--version"|"-h"|"-v")
        bw "$@"; exit $?
        ;;
esac

if ! bw login --check &>/dev/null; then
    EMAIL="$(rofi -dmenu -p 'Email' -l 0)"
    PASSWORD="$(rofi -dmenu -p 'Master Password' -password -l 0)"
    [ -z "${PASSWORD}" ] && exit 1
    SESSION="$(bw login "${EMAIL}" "${PASSWORD}")"
    [ -z "${SESSION}" ] && echo "Failed to unlock vault" && exit 1
    keyctl add user "bw_session" "${SESSION}" "@u" &>/dev/null || exit 1
fi

SESSION=$(keyctl pipe "$(keyctl request user "bw_session" 2> /dev/null)" 2> /dev/null)
STATUS="$(bw status --session "${SESSION}" | jq -r '.status')"
if [ "${STATUS}" = "locked" ]; then
    keyctl purge user "bw_session" &> /dev/null
    PASSWORD="$(rofi -dmenu -p 'Master Password' -password -l 0)"
    [ -z "${PASSWORD}" ] && exit 1
    SESSION="$(bw unlock "${PASSWORD}" --raw)"
    [ -z "${SESSION}" ] && echo "Failed to unlock vault" && exit 1
    keyctl add user "bw_session" "${SESSION}" "@u" &> /dev/null || exit 1
fi

if [ "${1}" = "ls" ]; then
    bw --session "${SESSION}" list items --search "${2}" | jq -r '.[] | [.name, .login.username, .login.password] | @tsv' | column -t
else
    bw --session "${SESSION}" "$@"
fi
