#!/bin/bash

# For best effect, add this line to i3 config:
# for_window [title="calendar.vim"] floating enable, resize set 800 600, move absolute position center

################# .calendar-vimrc: #################
#scriptencoding utf-8
#
#set backupdir=~/.nvim/backup//
#set directory=~/.nvim/swap//
#set noshowmode
#set noruler
#set laststatus=0
#set noshowcmd
#set clipboard=unnamedplus
#
#" Search settings
#    nnoremap / /\v
#    vnoremap / /\v
#    set ignorecase
#    set smartcase
#    set incsearch
#    set showmatch
#    set hlsearch
#
#    " clear search results on ESC double press
#    nnoremap <silent> <esc> :let @/ = ""<return><esc>
#    nnoremap <silent> <esc>^[ <esc>^[
#
#    " Case sensitive
#    nnoremap * /\C\<<C-R>=expand('<cword>')<CR>\><CR>
#    nnoremap # ?\C\<<C-R>=expand('<cword>')<CR>\><CR>
#
#let g:calendar_google_calendar = 1
#" map the q key to quit vim.
#"Using VimEnter callback so that it would override any plugin setting this mapping
#autocmd VimEnter * nmap <buffer> q :qa!<CR>
#execute pathogen#interpose('bundle/calendar.vim')
#set secure
####################################################

st -t 'calendar.vim-33b067d9-70a0-40df-9a11-dbe3e0b55ec6' -e nvim -u ~/.calendar-vimrc +Calendar 2>/dev/null
