#!/bin/bash

die() { echo "$*" >&2; exit 2; }  # complain to STDERR and exit with error
needs_arg() { if [ -z "$OPTARG" ]; then die "No arg for --$OPT option"; fi; }

while getopts ln-: OPT; do
  # support long options: https://stackoverflow.com/a/28466267/519360
  if [ "$OPT" = "-" ]; then   # long option: reformulate OPT and OPTARG
    OPT="${OPTARG%%=*}"       # extract long option name
    OPTARG="${OPTARG#$OPT}"   # extract long option argument (may be empty)
    OPTARG="${OPTARG#=}"      # if long option argument, remove assigning `=`
  fi
  case "$OPT" in
    n | nosteam )  nosteam=true ;;
    l | legacy )   legacy=true ;;
    ??* )          die "Illegal option --$OPT" ;;  # bad long option
    ? )            exit 2 ;;  # bad short option (error reported via getopts)
  esac
done
shift $((OPTIND-1)) # remove parsed options and args from $@ list

export WINEESYNC=1
export WINEDEBUG=-all
export DXVK_LOG_LEVEL=none
LEGACY=""
[ ${legacy} ] && LEGACY="+set legacymode 1"

gamemoderun wine cmd /c start /exec 'Z:\home\'"${USER}"'\Games\call-of-duty-4-modern-warfare\drive_c\Program Files (x86)\Activision\Call of Duty 4 - Modern Warfare\iw3mp.exe' "${LEGACY}" "$@" &

[ ${nosteam} ] || [ ${legacy} ] && echo "Running without steam" && exit 0

{ pgrep steam.exe &>/dev/null && echo "Steam already running"; } || { echo "Launching steam" && wine "/home/${USER}/.wine/drive_c/Program Files (x86)/Steam/steam.exe" -silent &> /dev/null & }
