#!/bin/bash

die() { echo "$*" >&2; exit 2; }  # complain to STDERR and exit with error
needs_arg() { if [ -z "$OPTARG" ]; then die "No arg for --$OPT option"; fi; }

while getopts ls-: OPT; do
  # support long options: https://stackoverflow.com/a/28466267/519360
  if [ "$OPT" = "-" ]; then   # long option: reformulate OPT and OPTARG
    OPT="${OPTARG%%=*}"       # extract long option name
    OPTARG="${OPTARG#$OPT}"   # extract long option argument (may be empty)
    OPTARG="${OPTARG#=}"      # if long option argument, remove assigning `=`
  fi
  case "$OPT" in
    s | steam )    steam=true ;;
    l | legacy )   legacy=true ;;
    ??* )          die "Illegal option --$OPT" ;;  # bad long option
    ? )            exit 2 ;;  # bad short option (error reported via getopts)
  esac
done
shift $((OPTIND-1)) # remove parsed options and args from $@ list

export STAGING_RT_PRIORITY_SERVER=90
export STAGING_RT_PRIORITY_BASE=90
export WINEESYNC=1
export WINEDEBUG=-all
export STAGING_SHARED_MEMORY=1
export STAGING_WRITECOPY=0 # might result in higher memory usage, but avoids COW
export DXVK_LOG_LEVEL=none
export DXVK_ASYNC=1
#export DXVK_HUD=full
LEGACY=""
[ "${legacy}" ] && LEGACY="+set legacymode 1"

#~/compiled/wine/build64/server/wineserver -k
#~/compiled/wine/build64/server/wineserver
~/compiled/wine/build32/wine "/home/${USER}/.wine/drive_c/Program Files (x86)/Activision/Call of Duty 4 - Modern Warfare/iw3mp.exe" "${LEGACY}" "$@" 2>/dev/null &
#~/compiled/wine/build32/wine "/home/${USER}/.wine/drive_c/Program Files (x86)/Activision/Call of Duty 4 - Modern Warfare/cod4x_game.exe" "${LEGACY}" "$@" 2>/dev/null &

[ ! "${steam}" ] && exit 0

{ pgrep steam.exe &>/dev/null && echo "Steam already running"; } || { echo "Launching steam" && ~/compiled/wine/build32/wine "/home/${USER}/.wine/drive_c/Program Files (x86)/Steam/steam.exe" -silent &> /dev/null & }

