#!/bin/bash

[ "X$(command -v bc)" = "X" ] && echo "bc not installed" && exit

TEMPS=()
while read -r temp; do
    TEMPS+=("${temp}")
done <<< "$(sensors | sed -n '/Package id/,/^$/p' | perl -n -e '/:\s+\+(\d+)/ && print $1."\n"')"

TEMP_SUM=0
for i in "${!TEMPS[@]}"; do
    TEMP_SUM=$(( TEMP_SUM +  TEMPS[i] ))
done

echo "${TEMP_SUM} / ${#TEMPS[@]}" | bc
