#!/bin/bash

cipherFilename="$1"
plaintextFilename="${cipherFilename%.gpg}"

if [ -f "${plaintextFilename}" ]; then
    read -r -e -p "File ${plaintextFilename} already exists, overwrite? [y/N] " YN
    [[ $YN != "y" && $YN != "Y" ]] && echo "Operation canceled." && exit 0;
fi

gpg -d "${cipherFilename}" > "${plaintextFilename}"
