#!/bin/bash

accounts=$(grep -v "^#" .lpass-accounts)
accountNames=$(echo "${accounts}" | cut -d ':' -f1)
chosenAccountName=$(echo "${accountNames}" | dmenu -i -l 10)

# Nothing selected, exit
[ "${chosenAccountName}" != "" ] || exit

chosenAccontEmail=$(echo "${accounts}" | grep "${chosenAccountName}:" | cut -d ':' -f2)

# Already logged in to this account
lpass status | grep "${chosenAccontEmail}" && notify-send "${chosenAccountName} account already active." && exit

message=$(lpass login ${chosenAccontEmail})
notify-send "${message}"

