#!/bin/bash

# amixer get Master | grep -oE '\[[0-9]+%' | head -n1 | grep -oE '[0-9]+'
#pamixer --get-volume
pactl get-sink-volume @DEFAULT_SINK@ | head -n1 | awk -F'/' '{print $2}' | grep -Eo "[0-9]+"

