#!/bin/bash

#state=$(amixer get Master | grep -oE "\[(on|off)\]" | head -n1)
#if [ "${state}" == "[on]" ]; then
#	echo "false"
#elif [ "${state}" == "[off]" ]; then
#	echo "true"
#else
#	echo "error getting state"
#fi

#pamixer --get-mute || true

state="$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')"
{ [ "${state}" = "yes" ] && echo "true"; } || echo "false"
