#!/bin/bash

# MIT License
# 
# Copyright (c) 2023 Marek Bogusovsky
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

function _c() {
    xrdb -quiet -get "$1" | tr -d '\n'
}

function toColor() {
    [ "${1:0:1}" == "#" ] && echo -n "${1}" && return 0
    case $1 in
         "0" | "black"        |   "color0")   _c color0 ;;
         "1" | "red"          |   "color1")   _c color1 ;;
         "2" | "green"        |   "color2")   _c color2 ;;
         "3" | "yellow"       |   "color3")   _c color3 ;;
         "4" | "blue"         |   "color4")   _c color4 ;;
         "5" | "magenta"      |   "color5")   _c color5 ;;
         "6" | "cyan"         |   "color6")   _c color6 ;;
         "7" | "white"        |   "color7")   _c color7 ;;
         "8" | "l-black"      |   "color8")   _c color8 ;;
         "9" | "l-red"        |   "color9")   _c color9 ;;
        "10" | "l-green"      |   "color10")  _c color10 ;;
        "11" | "l-yellow"     |   "color11")  _c color11 ;;
        "12" | "l-blue"       |   "color12")  _c color12 ;;
        "13" | "l-magenta"    |   "color13")  _c color13 ;;
        "14" | "l-cyan"       |   "color14")  _c color14 ;;
        "15" | "l-white"      |   "color15")  _c color15 ;;
        *) echo -n "#ff00e0" ;; # error color
    esac
}

function colorize() {
  [ "$1" = '-n' ] && FLAGS=("-n") && shift
  echo "${FLAGS[@]}" "%{F$(toColor "${1}")}${2}%{F-}"
}

function colorizeBegin() {
  echo -n "%{F$(toColor "${1}")}"
}

function colorizeEnd() {
  echo "$@" "%{F-}"
}

function interpolateColor() {
    color-map "$(toColor "${1}")" "$(toColor "${2}")" "${3}"
}
