#!/bin/bash

# MIT License
# 
# Copyright (c) 2020 Marek Bogusovsky
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

function toColor() {
    [ ${1:0:1} == "#" ] && echo -n "${1}" && return 0
    case $1 in
        "gray") echo -n "#acacac" ;;
        "magenta") echo -n "#8D20AE" ;;
        "green") echo -n "#a6e22e" ;;
        "red") echo -n "#ba3232" ;;
        *) echo -n "#ff00e0" ;; # error colour
    esac
}

function printColor() {
    echo $(toColor $1) && echo $(toColor $1)
}

function colorize {
  echo "<span foreground=\"$(toColor $1)\">${2}</span>"
}

function colorizeBegin {
  echo -n "<span foreground=\"$(toColor $1)\">"
}

function colorizeEnd {
  echo $@ "</span>"
}

function interpolateColor {
    color-map "${1}" "${2}" "${3}"
}
