#!/bin/bash

# MIT License
# 
# Copyright (c) 2020 Marek Bogusovsky
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

case ${BLOCK_BUTTON} in
    1) notify-send "CPU hogs:" "$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)" ;;
esac

source colors

CPU_TEMP=$(cpu-core-temp)
CPU_MAX=70

LABELS=""

# ( (${CPU_TEMP} + (${CPU_MAX} / 5)) / (${CPU_MAX} / 5) ) * 4 / 5 ==
# ((x + (y / 5)) / (y / 5)) * 4 / 5 ==
LABEL_INDEX=$(( 4 * (${CPU_TEMP} + ${CPU_MAX} / 5) / ${CPU_MAX} ))
LABEL=${LABELS:${LABEL_INDEX}:1}

COLOR=$(interpolateColor "#00ff00" "#ff0000" $(( ${CPU_TEMP} * 100 / ${CPU_MAX} )) )

echo -n "${LABEL} "
colorizeBegin ${COLOR}
echo -n "${CPU_TEMP}°C"
colorizeEnd

